In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.6.0+cu124


## Introduction to tensors

### Creating tensors

#### PyTorch tensors are created `using torch.Tensors` = https://pytorch.org/docs/stable/tensors.html



In [3]:
# scalar

scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
 # Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 8])
vector

tensor([7, 8])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[1, 2],
                       [3, 4]
                       ])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0][1]

tensor(2)

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

#### Why random tensors?

Random tensors are important because the way neural networks starts learning is that with full of random tensors and adjust those random numbers to better represent data

`Start random numbers -> look at the data -> update random numbers -> look at data -> update random number`

In [17]:
randNums = torch.randn(2, 10, 10)
randNums

tensor([[[-0.1913,  0.5292, -0.3886,  1.5012, -0.5983,  0.5354,  1.2683,
          -0.1451, -0.7761, -1.6147],
         [ 0.1320, -0.4637, -0.1504, -0.7825,  0.7085,  1.5675,  0.4460,
          -1.0196,  0.0906,  2.0887],
         [-0.4942,  1.8428, -0.1477, -0.6447, -1.7809, -0.4566, -1.0128,
          -0.0829, -2.0774,  1.2582],
         [ 0.2941,  0.6032,  1.8677, -2.0157, -0.6031, -1.5040,  1.0042,
          -0.8074, -0.5925, -0.1058],
         [-0.1103, -1.1416, -0.0243, -0.0771,  1.0048, -1.3013, -1.1381,
           2.0205, -0.4948,  1.2587],
         [-2.4318, -1.0322,  0.1904,  1.3810,  0.4728, -0.2766, -0.6104,
           0.5812, -0.3908, -0.1162],
         [ 0.3129,  0.3813,  0.3605, -1.9147, -1.1542,  1.2272, -0.1973,
           0.7812,  1.3714,  1.1427],
         [ 0.2146, -0.4924,  0.4352,  1.6730,  1.9345, -0.8742, -1.5173,
          -0.3206,  1.1327,  0.0401],
         [-0.7692, -1.0708,  0.5358, -0.8776,  1.6735,  0.5588, -0.8769,
           1.1360, -0.2841, -0.1322],
 

In [18]:
randNums.ndim

3

In [19]:
random_image_size_tensor = torch.randn(size=(3, 224, 224)) # height, width, color channels (R, G, B)

In [20]:
random_image_size_tensor


tensor([[[ 0.9798,  1.4074,  0.6751,  ..., -0.3037, -1.6031, -0.5730],
         [ 0.2425, -0.3639, -0.3383,  ...,  0.1293, -0.0696,  1.8037],
         [ 1.1026,  0.9610,  0.1531,  ...,  0.3915, -0.3913, -0.4200],
         ...,
         [ 0.6178, -0.8388,  0.5591,  ...,  0.7709, -0.1306, -0.5426],
         [ 0.1273, -0.4294,  1.3059,  ...,  0.0068, -1.1193,  0.7992],
         [ 1.3191,  0.1629, -1.7156,  ...,  0.4956, -0.6049, -1.2933]],

        [[ 0.9310,  0.6393, -1.0244,  ..., -1.5814,  0.4964, -1.1107],
         [ 0.0955,  0.1296, -2.0967,  ...,  0.7469, -2.3636, -0.1669],
         [ 1.7086,  0.4769, -0.2689,  ..., -1.1504, -0.4027,  0.3914],
         ...,
         [ 0.8595,  0.9852,  0.0221,  ...,  0.8790, -1.0361,  0.1598],
         [ 1.0844,  0.8064,  1.3322,  ...,  1.9630,  1.1735,  0.5870],
         [ 1.3757, -0.3795,  0.1954,  ..., -0.8206, -0.7423,  0.1077]],

        [[-1.0973,  0.5330, -0.9523,  ..., -1.1923, -0.2692, -0.3977],
         [-0.8592, -0.2970, -0.3690,  ...,  0

In [21]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [22]:
torch.randn(3, 3)

tensor([[-1.1923,  0.5027,  0.7903],
        [ 1.8266, -0.9711, -0.8303],
        [-1.6659,  0.6798, -0.8082]])

In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
random_tensor = torch.randn(3,4)

In [25]:
zeros@random_tensor.T

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [28]:
# Use torch.range()

In [29]:
one_to_ten = torch.arange(start=1, end=11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
zeros_like = torch.zeros_like(input = one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
#### **Node:** Tensor datatypes is one of the 3 big errors that you'll run into with PyTorch & deep learning:

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors are not on the right device









In [31]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64, #What datatype is tensor
                               device=None,
                               requires_grad=False
                               )
float_32_tensor.dtype

torch.float64

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [33]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [34]:
some_tensor = torch.randn([3, 4])

In [35]:
# Find out details about some tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[ 0.7100,  0.5670,  0.0346,  1.8151],
        [-0.9052,  0.3164, -0.9017, -0.2993],
        [ 1.4375, -2.6108, -0.4233, -0.8643]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

#### Tensor operations include:


*   Addition
*   Subtraction
*   Multiplication (element-wise)
*   Division
*   Matrix multiplication






In [36]:
tensor = torch.tensor([1,2,3,4])
tensor+20

tensor([21, 22, 23, 24])

In [37]:
tensor*20

tensor([20, 40, 60, 80])

In [38]:
tensor-20

tensor([-19, -18, -17, -16])

In [39]:
 torch.mul(tensor, 20)

tensor([20, 40, 60, 80])

In [40]:
 torch.add(tensor, 20)

tensor([21, 22, 23, 24])

### MAtrix multiplication

Two ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication

In [41]:
tensor = torch.tensor([1,2,3])
tensor*tensor

tensor([1, 4, 9])

In [42]:
torch.matmul(tensor, tensor)

tensor(14)

### To fix our tensor issues, we can manipulate the shape of one of our tensors using transpose matrix operation

In [43]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

In [44]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [45]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [46]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

### Finding min, max, mean, sum, etc (tensor aggregation)

In [47]:
# Create a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
# Find the min
torch.min(x)

tensor(0)

In [49]:
# Find the max value from a vector tensor

torch.max(x)

tensor(90)

In [50]:
x = x.type(torch.float16)

In [51]:
# Find a mean value

torch.mean(x)

tensor(45., dtype=torch.float16)

In [52]:
torch.sum(x)

tensor(450., dtype=torch.float16)

## Finding the positional min and max

In [53]:
x.argmin()

tensor(0)

In [54]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memomry as the original tensor
* Stacking - combine multiple tensors on top each other (vstack, hstack )

In [55]:
# Let's create a tensor

import torch
x = torch.arange(1., 11.)

In [56]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
# Add an extra dimention

x_reshaped = x.reshape(1, 10)

In [58]:
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [59]:
x.reshape(10, 1)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [60]:
x.reshape(5, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [61]:
z = x.view(1, 10)

In [62]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [63]:
# Stack tensors on top each other

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [64]:
x

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
# torch.squeeze() - removes all single dimensions froma target tensors

x = torch.zeros(2, 1, 2, 1, 2)

In [66]:
x.squeeze().unsqueeze(dim=2).unsqueeze(dim=3).shape

torch.Size([2, 2, 1, 1, 2])

In [67]:
# torch.permute - rearranges the dimension of a target tensor in a specified order

In [68]:
x = torch.randn(2, 3, 5)
x

tensor([[[ 0.9213,  1.4068,  0.0092, -1.5624,  0.3334],
         [-2.0164,  0.0803, -1.5573,  0.5513, -1.2946],
         [ 0.4792, -1.5502, -1.1045,  0.7657,  0.8135]],

        [[-1.3780, -0.2335, -0.3003, -1.1516,  1.1394],
         [-0.1731,  1.5778,  0.2164,  1.5499,  1.7555],
         [-0.0427, -0.4873, -0.8174, -2.2776, -0.6765]]])

In [69]:
torch.permute(x, (2, 0, 1)).shape

torch.Size([5, 2, 3])

In [70]:
torch.permute(x, (2, 0, 1))

tensor([[[ 0.9213, -2.0164,  0.4792],
         [-1.3780, -0.1731, -0.0427]],

        [[ 1.4068,  0.0803, -1.5502],
         [-0.2335,  1.5778, -0.4873]],

        [[ 0.0092, -1.5573, -1.1045],
         [-0.3003,  0.2164, -0.8174]],

        [[-1.5624,  0.5513,  0.7657],
         [-1.1516,  1.5499, -2.2776]],

        [[ 0.3334, -1.2946,  0.8135],
         [ 1.1394,  1.7555, -0.6765]]])

In [71]:
image_tensor = torch.randn(size = (224, 224, 3))

image_tensor.permute(2, 0, 1).shape

torch.Size([3, 224, 224])

In [72]:
  # Create tensor

import torch
x = torch.arange(1,10).reshape(1,3,3)

In [73]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
x[0][0][0]

tensor(1)

In [78]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [80]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))